In [1]:
print("Hello World!")

Hello World!


In [2]:
if 5>2:
    print("Five is greater than two!")

Five is greater than two!


In [3]:
if 5 > 2:
 print("wow")
 print("wow")

wow
wow


In [12]:
#Variable Types
x = 5
y = "John"

print(type(x), type(y))

x = str(3)
y = int(3)
z = float(3)

print(type(x), type(y), type(z))

#illegal names
#2myvar
#my-var
#my var 

x, y, z = "Orange", "Banana", "Cherry"
print(x,y,z)

#UNPACK COLLECTION
fruits = ["apple", "banana", "cherry"]
x, y, z = fruits
print(x, y, z)

#Global Keyword
def myfunc():
    global x
    x = "fantastic"
myfunc()

print(x)

<class 'int'> <class 'str'>
<class 'str'> <class 'int'> <class 'float'>
Orange Banana Cherry
apple banana cherry
fantastic


In [11]:
#Data Types
x = 1j
print(type(x))
x = ["apple", "banana", "cherry"]
print(type(x))
x = ("apple", "banana", "cherry")
print(type(x))
x = range(6)
print(type(x))
x = {"name" : "John", "age" : 36}
print(type(x))
x = {"apple", "banana", "cherry"}
print(type(x))
x = frozenset({"apple", "banana", "cherry"})
print(type(x))
x = b"Hello"
print(type(x))
x = bytearray(5)
print(type(x))
x = memoryview(bytes(5))
print(type(x))
x = None
print(type(x))

<class 'complex'>
<class 'list'>
<class 'tuple'>
<class 'range'>
<class 'dict'>
<class 'set'>
<class 'frozenset'>
<class 'bytes'>
<class 'bytearray'>
<class 'memoryview'>
<class 'NoneType'>


In [20]:
import random

print(random.randrange(1, 10)) #rand num between 1-9

7


In [22]:
a = """one hundren
fooooorty
zebras
thirteen
 people.
"""
print(a)

one hundren
fooooorty
zebras
thirteen
 people.



In [7]:
#Strings as Arrays, charAt()
a = "Hello, World!"
print(a[1])

#looping structure
for x in "juan":
    print(x)

print(len(a))

#different ways of checking string
if "Hell" in a:
    print("yes", "know" not in a)

#slicing string
print(a[2:5])
print(a[:4])
print(a[::-1])

#modifying string
print(a[:5].upper())
print(a[4::-1].lower())

#strip
b = "       hi        "
print(b.strip())

#replace
print(a.replace("He","'a"))

#split string
print(a.split(','))

e
j
u
a
n
13
yes True
llo
Hell
!dlroW ,olleH
HELLO
olleh
hi
'allo, World!
['Hello', ' World!']


In [17]:
temp = 36
txt = "the temperature is {}"
print(txt.format(temp))

quant = 3
itemno = 123
price = 43.66
myorder = "i want {} of {} for {}" 
print(myorder.format(quant,itemno,price))
myorder = "i want {2} of {0} for {1}" #can index for which variable goes where
print(myorder.format(quant,itemno,price))


the temperature is 36
i want 3 of 123 for 43.66
i want 43.66 of 3 for 123


In [21]:
print(bool(False),bool(None)
,bool(0)
,bool("")
,bool(())
,bool([])
,bool({}))
x = 200
print(isinstance(x, int))

False False False False False False False
True


In [38]:
#LIST
thislist = ["apple", "banana", "cherry"]
print(thislist)

thislist = ["apple", "banana", "cherry", "apple", "cherry"]
print(thislist)

thislist = ["apple", "banana", "cherry"]
print(len(thislist))

thislist = list(("apple", "banana", "cherry")) # note the double round-brackets ##USES LIST CONSTRUCTOR
print(thislist)

print(thislist[1])

print(thislist[-1])

thislist = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
print(thislist[2:5])
thislist[1] = "blackcurrant"
print(thislist)

thislist[1:2] = ["blueberry", "watermelon"]
print(thislist)
thislist[1:3] = ["watermelon"]
print(thislist)

thislist = ["apple", "banana", "cherry"]
thislist.insert(2, "watermelon")
print(thislist)

thislist.append("orange")
print(thislist)

thislist = ["apple", "banana", "cherry"]
tropical = ["mango", "pineapple", "papaya"]
thislist.extend(tropical)
print(thislist)

thistuple = ("kiwi", "orange")
thislist.extend(thistuple)
print(thislist)

thislist.remove("banana")
print(thislist)

thislist.pop(1)
print(thislist)

thislist.pop()
print(thislist)

del thislist[0]
print(thislist)

del thislist

thislist = ["apple", "banana", "cherry"]
thislist.clear()
print(thislist)

['apple', 'banana', 'cherry']
['apple', 'banana', 'cherry', 'apple', 'cherry']
3
['apple', 'banana', 'cherry']
banana
cherry
['cherry', 'orange', 'kiwi']
['apple', 'blackcurrant', 'cherry', 'orange', 'kiwi', 'melon', 'mango']
['apple', 'blueberry', 'watermelon', 'cherry', 'orange', 'kiwi', 'melon', 'mango']
['apple', 'watermelon', 'cherry', 'orange', 'kiwi', 'melon', 'mango']
['apple', 'banana', 'watermelon', 'cherry']
['apple', 'banana', 'watermelon', 'cherry', 'orange']
['apple', 'banana', 'cherry', 'mango', 'pineapple', 'papaya']
['apple', 'banana', 'cherry', 'mango', 'pineapple', 'papaya', 'kiwi', 'orange']
['apple', 'cherry', 'mango', 'pineapple', 'papaya', 'kiwi', 'orange']
['apple', 'mango', 'pineapple', 'papaya', 'kiwi', 'orange']
['apple', 'mango', 'pineapple', 'papaya', 'kiwi']
['mango', 'pineapple', 'papaya', 'kiwi']
[]


In [40]:
fruits = ["apple", "banana", "cherry", "kiwi", "mango"]
newlist = []

for x in fruits:
  if "a" in x:
    newlist.append(x)

print(newlist)

fruits = ["apple", "banana", "cherry", "kiwi", "mango"]

newlist = [x for x in fruits if "a" in x] #[(expression) for (item) in (iterable) if (condition == True)]

print(newlist)

['apple', 'banana', 'mango']
['apple', 'banana', 'mango']


In [48]:
thislist = ["orange", "mango", "kiwi", "pineapple", "banana"]
thislist.sort()
print(thislist)

thislist = [100, 50, 65, 82, 23]
thislist.sort()
print(thislist)

thislist = ["orange", "mango", "kiwi", "pineapple", "banana"]
thislist.sort(reverse = True)
print(thislist)

#CUSTOM SORT FUNCTION

def myfunc(n):
  return abs(n - 50) #Sort list based on how close the number is to 50
def myfunc2(n):
  return abs(n-70) #close to 70

thislist = [100, 50, 65, 82, 23]
thislist.sort(key = myfunc)
print(thislist)
thislist.sort(key = myfunc2)
print(thislist)

thislist = ["banana", "Orange", "Kiwi", "cherry"]
thislist.sort(key = str.lower)
print(thislist)

thislist.reverse()
print(thislist)

thislist = ["apple", "banana", "cherry"]
mylist = thislist.copy()
print(mylist)

thislist = ["apple", "banana", "cherry"]
mylist = list(thislist)
print(mylist)

['banana', 'kiwi', 'mango', 'orange', 'pineapple']
[23, 50, 65, 82, 100]
['pineapple', 'orange', 'mango', 'kiwi', 'banana']
[50, 65, 23, 82, 100]
[65, 82, 50, 100, 23]
['banana', 'cherry', 'Kiwi', 'Orange']
['Orange', 'Kiwi', 'cherry', 'banana']
['apple', 'banana', 'cherry']
['apple', 'banana', 'cherry']


In [50]:
list1 = ["a", "b", "c"]
list2 = [1, 2, 3]

list3 = list1 + list2
print(list3)

for x in list2:
  list1.append(x)

print(list1)

list2.extend(list2)
print(list2)

"""
METHODS
append()	Adds an element at the end of the list
clear()	    Removes all the elements from the list
copy()	    Returns a copy of the list
count()	    Returns the number of elements with the specified value
extend()    Add the elements of a list (or any iterable), to the end of the current list
index()	    Returns the index of the first element with the specified value
insert()	Adds an element at the specified position
pop()	    Removes the element at the specified position
remove()	Removes the item with the specified value
reverse()	Reverses the order of the list
sort()	    Sorts the list
"""

['a', 'b', 'c', 1, 2, 3]
['a', 'b', 'c', 1, 2, 3]
[1, 2, 3, 1, 2, 3]


'\nMETHODS\nappend()\tAdds an element at the end of the list\nclear()\t    Removes all the elements from the list\ncopy()\t    Returns a copy of the list\ncount()\t    Returns the number of elements with the specified value\nextend()    Add the elements of a list (or any iterable), to the end of the current list\nindex()\t    Returns the index of the first element with the specified value\ninsert()\tAdds an element at the specified position\npop()\t    Removes the element at the specified position\nremove()\tRemoves the item with the specified value\nreverse()\tReverses the order of the list\nsort()\t    Sorts the list\n'

In [53]:
x = lambda a, b : a * b
print(x(5, 6))

def myfunc(n):
  return lambda a : a * n

mydoubler = myfunc(2)

print(mydoubler(11))

def myfunc(n):
  return lambda a : a * n

mydoubler = myfunc(2)
mytripler = myfunc(3)

print(mydoubler(11))
print(mytripler(11))

30
22
22
33


In [3]:
class Person:
  def __init__(self, fname, lname):
    self.firstname = fname
    self.lastname = lname

  def printname(self):
    print(self.firstname, self.lastname)

#Use the Person class to create an object, and then execute the printname method:

x = Person("John", "Doe")
x.printname()

class Student(Person):
  pass

x = Student("Mike", "Olsen")
x.printname()

class Worker(Person):
    def __init__(self,fname,lname,year):
        super().__init__(fname,lname)
        self.workingyear = year
    def welcome(self):
        print("Welcome",self.firstname,self.lastname,"to the year of",self.workingyear)

x = Worker("Brad","Paisley",2077)
x.welcome()

John Doe
Mike Olsen
Welcome Brad Paisley to the year of 2077


In [4]:
mytuple = ("apple", "banana", "cherry")
myit = iter(mytuple)

print(next(myit))
print(next(myit))
print(next(myit))

mystr = "banana"
myit = iter(mystr)

print(next(myit))
print(next(myit))
print(next(myit))
print(next(myit))
print(next(myit))
print(next(myit))

class MyNumbers:
  def __iter__(self):
    self.a = 1
    return self

  def __next__(self):
    x = self.a
    self.a += 1
    return x

myclass = MyNumbers()
myiter = iter(myclass)

print(next(myiter))
print(next(myiter))
print(next(myiter))
print(next(myiter))
print(next(myiter))

apple
banana
cherry
b
a
n
a
n
a
1
2
3
4
5


In [5]:
class MyNumbers:
  def __iter__(self):
    self.a = 1
    return self

  def __next__(self):
    if self.a <= 20:
      x = self.a
      self.a += 1
      return x
    else:
      raise StopIteration

myclass = MyNumbers()
myiter = iter(myclass)

for x in myiter:
  print(x)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [6]:
import platform

x = platform.system()
print(x)

import platform

x = dir(platform)
print(x)



Windows
['_Processor', '_WIN32_CLIENT_RELEASES', '_WIN32_SERVER_RELEASES', '__builtins__', '__cached__', '__copyright__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '__version__', '_comparable_version', '_component_re', '_default_architecture', '_follow_symlinks', '_get_machine_win32', '_ironpython26_sys_version_parser', '_ironpython_sys_version_parser', '_java_getprop', '_libc_search', '_mac_ver_xml', '_node', '_norm_version', '_os_release_cache', '_os_release_candidates', '_os_release_line', '_os_release_unescape', '_parse_os_release', '_platform', '_platform_cache', '_pypy_sys_version_parser', '_sys_version', '_sys_version_cache', '_sys_version_parser', '_syscmd_file', '_syscmd_ver', '_uname_cache', '_unknown_as_blank', '_ver_output', '_ver_stages', 'architecture', 'collections', 'freedesktop_os_release', 'functools', 'itertools', 'java_ver', 'libc_ver', 'mac_ver', 'machine', 'node', 'os', 'platform', 'processor', 'python_branch', 'python_build', 'py

In [72]:
import datetime

x = datetime.datetime.now()
print(x)

import datetime

x = datetime.datetime.now()

print(x.year)
print(x.strftime("%A"))
print(x.strftime("%A %a %Y %I:%M.%S %p %Z WEEK:%U"))

2022-11-29 20:06:39.182141
2022
Tuesday
Tuesday Tue 2022 08:06.39 PM  WEEK:48


In [73]:
x = min(5, 10, 25)
y = max(5, 10, 25)

print(x)
print(y)

5
25


In [76]:
import math

x = math.sqrt(64)

print(x)

x = math.ceil(1.4)
y = math.floor(1.4)

print(x) # returns 2
print(y) # returns 1

x = math.pi

print(x)

8.0
2
1
3.141592653589793


In [81]:
import json

# some JSON:
x =  '{ "name":"John", "age":30, "city":"New York"}'

# parse x:
y = json.loads(x)

# the result is a Python dictionary:
print(y["age"])

# a Python object (dict):
x = {
  "name": "John",
  "age": 30,
  "city": "New York"
}

# convert into JSON:
y = json.dumps(x)

# the result is a JSON string:
print(y)

print(json.dumps({"name": "John", "age": 30}))
print(json.dumps(["apple", "bananas"]))
print(json.dumps(("apple", "bananas")))
print(json.dumps("hello"))
print(json.dumps(42))
print(json.dumps(31.76))
print(json.dumps(True))
print(json.dumps(False))
print(json.dumps(None))

x = {
  "name": "John",
  "age": 30,
  "married": True,
  "divorced": False,
  "children": ("Ann","Billy"),
  "pets": None,
  "cars": [
    {"model": "BMW 230", "mpg": 27.5},
    {"model": "Ford Edge", "mpg": 24.1}
  ]
}

print(json.dumps(x))
print(json.dumps(x, indent=4, separators=(". ", " = ")))

30
{"name": "John", "age": 30, "city": "New York"}
{"name": "John", "age": 30}
["apple", "bananas"]
["apple", "bananas"]
"hello"
42
31.76
true
false
null
{"name": "John", "age": 30, "married": true, "divorced": false, "children": ["Ann", "Billy"], "pets": null, "cars": [{"model": "BMW 230", "mpg": 27.5}, {"model": "Ford Edge", "mpg": 24.1}]}
{
    "name" = "John". 
    "age" = 30. 
    "married" = true. 
    "divorced" = false. 
    "children" = [
        "Ann". 
        "Billy"
    ]. 
    "pets" = null. 
    "cars" = [
        {
            "model" = "BMW 230". 
            "mpg" = 27.5
        }. 
        {
            "model" = "Ford Edge". 
            "mpg" = 24.1
        }
    ]
}


In [96]:
import re

txt = "The rain in Spain"
x = re.search("^The.*Spain$", txt) #SEARCH IF STRING STARTS WITH "THE" and ENDS WITH "SPAIN"
print(x)
x = re.search("^The.*Spain$","The trees are not spanish")
print(x)

x = re.findall("ai", txt)
print(x)

x = re.search("\s", txt)

print("The first white-space character is located in position:", x.start())

x = re.split("\s", txt)
print(x)

x = re.split("\s", txt, 1)
print(x)

x = re.sub("\s", "9", txt)
print(x)

x = re.search("ai", txt)
print(x) #this will print an object

x = re.search(r"\bS\w+", txt)
print(x.span())

x = re.search(r"\bS\w+", txt)
print(x.string)

x = re.search(r"\bS\w+", txt)
print(x.group())

"""
The Match object has properties and methods used to retrieve information about the search, and the result:
.span() returns a tuple containing the start-, and end positions of the match.
.string returns the string passed into the function
.group() returns the part of the string where there was a match
"""

<re.Match object; span=(0, 17), match='The rain in Spain'>
None
['ai', 'ai']
The first white-space character is located in position: 3
['The', 'rain', 'in', 'Spain']
['The', 'rain in Spain']
The9rain9in9Spain
<re.Match object; span=(5, 7), match='ai'>
(12, 17)
The rain in Spain
Spain


In [1]:
#NUMPY START
import numpy
arr = numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [23]:
import numpy as np
print(np.__version__)
arr = np.array([1,2,3,4,5]) #list passed
print(type(arr))

arr = np.array((1,2,3,4,5)) #tuple passed
print(type(arr))

arr = np.array(42) #0d arr
print(arr)

arr = np.array([1,2,3,4,5]) #1d arr

arr = np.array([[1,2,3],[4,5,6]]) #2d arr
print(arr)

arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) #3d arr
print(arr)

print(arr.ndim) #returns int of array's dimensions

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
print(arr[1,0]) #dim index sep by comma
print(arr[-1]) #print last index

arr = np.array([1, 2, 3, 4])
print(arr.dtype)

arr = np.array([1, 2, 3, 4], dtype='S')
print(arr.dtype)

arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr, newarr.dtype)
arr = newarr.copy()
print(arr)

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[-1] = 6000
print(arr)
print(x)
arr = np.concatenate((arr, np.array([7,8,9])))
print(arr)
print(x.base)
print(arr.base)

1.23.5
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
42
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
[[[[[1 2 3 4]]]]]
number of dimensions : 5
50
[50 60 70 80]
int32
|S1
[1 2 3] int32
[1 2 3]
[   1    2    3    4 6000]
[   1    2    3    4 6000]
[   1    2    3    4 6000    7    8    9]
[   1    2    3    4 6000]
None


In [29]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape) #2 dim, 4 elm each

arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('shape of array :', arr.shape) #1dim, 1dim ,1dim, 1dim, 1dim with 4 elm

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)
print(newarr)

arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr): #iterator
  print(x)

(2, 4)
[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[1 2 3 4 5 6]
1
2
3
4
5
6
7
8


In [32]:
import numpy as np

arr = np.array([1, 2, 3])
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(arr[:, ::2]):
  print(x)

for idx, x in np.ndenumerate(arr):
  print(idx, x)

b'1'
b'2'
b'3'
1
3
5
7
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [37]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
print(arr)

arr = np.hstack((arr1, arr2))
print(arr)

arr = np.vstack((arr1, arr2))
print(arr)

arr = np.dstack((arr1, arr2))
print(arr)

arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)



[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[1 4]
  [2 5]
  [3 6]]]
[array([1, 2]), array([3, 4]), array([5, 6])]


In [42]:
#PANDAS start
import pandas as pd

mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}

myvar = pd.DataFrame(mydataset)
print(myvar)

a = [1, 7, 2]
myvar = pd.Series(a)
print(myvar)
print(myvar[0])

myvar = pd.Series(a, index = ["x", "y", "z"])
print(myvar)
print(myvar["y"])


    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2
0    1
1    7
2    2
dtype: int64
1
x    1
y    7
z    2
dtype: int64
7


In [49]:
calories = {"day1": 420, "day2": 380, "day3": 390}
myvar = pd.Series(calories)
print(myvar)
myvar = pd.Series(calories, index = ["day1", "day2"])
print(myvar)

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}
myvar = pd.DataFrame(data)
print(myvar)
#refer to the row index:
print(myvar.loc[0])
#use a list of indexes:
print(myvar.loc[[0,1]])

day1    420
day2    380
day3    390
dtype: int64
day1    420
day2    380
dtype: int64
   calories  duration
0       420        50
1       380        40
2       390        45
calories    420
duration     50
Name: 0, dtype: int64
   calories  duration
0       420        50
1       380        40


In [51]:
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}
df = pd.DataFrame(data, index = ["day1", "day2", "day3"])
print(df)
#refer to the named index:
print(df.loc["day2"])

      calories  duration
day1       420        50
day2       380        40
day3       390        45
calories    380
duration     40
Name: day2, dtype: int64


In [61]:
#PYTHON BUBBLE SORT
import random
l = []
for i in range(20):
    l.append(random.randrange(100))
print(l)

for x in range(20 - 1):
    for y in range(20 - x - 1):
        if l[y] > l[y+1]:
            temp = l[y]
            l[y] = l[y+1]
            l[y+1] = temp
print(l)

[35, 92, 85, 78, 64, 25, 57, 72, 77, 91, 69, 44, 60, 86, 64, 59, 96, 99, 88, 0]
[0, 25, 35, 44, 57, 59, 60, 64, 64, 69, 72, 77, 78, 85, 86, 88, 91, 92, 96, 99]


In [ ]:
#MATPLOTLIB START
import matplotlib.pyplot as plt
